config/routes.rb
Rails.application.routes.draw do
  post 'add', to: 'friendships#add'
  get 'friends', to: 'users#friends'
  get 'search_users', to: 'users#searchu'
  get 'user_stocks/create'
  devise_for :users
  root 'welcome#index'
  get 'welcome/index'
  get 'search_stock', to: 'stocks#search'
  get 'my_portfolio', to: 'users#my_portfolio'
  resources :user_stocks, only: %i[create destroy]
  resources :users, only: %i[show]
  resources :friendships, only: %i[destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
# Friendship model
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
# stock model
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  def self.new_from_lookup(ticker)
    begin
      looked_up_stock = StockQuote::Stock.quote(ticker)
      new(name: looked_up_stock.company_name, ticker: looked_up_stock.symbol,
          last_price: looked_up_stock.latest_price)
    rescue StandardError
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_stocks, dependent: :destroy
  has_many :stocks, through: :user_stocks
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  def stock_already_added?(ticker)
    stock = Stock.find_by_ticker(ticker)
    return false unless stock

    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def can_add_stock?(ticker)
    under_stock_limit? && !stock_already_added?(ticker)
  end

  def full_name
    return "#{first_name} #{last_name}".strip if first_name || last_name

    'Anonymous'
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
# Appicatin controller
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

end

app/controllers/friendships_controller.rb
# Friendship controller
class FriendshipsController < ApplicationController
  def destroy
    id = params[:id]
    current_user.friendships.find_by_friend_id(id).destroy
    redirect_to friends_url
  end

  def add
    @friend = User.find(params[:friend])
    current_user.friends << @friend
    redirect_to friends_url
  end
end

app/controllers/stocks_controller.rb
# stocks controler
class StocksController < ApplicationController
  def search
    if params[:stock].blank?
      flash.now[:danger] = 'Stock name cannot be empty'
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:danger] = 'Invalid name' unless @stock
    end
    render 'users/search'
  end
end

app/controllers/user_stocks_controller.rb
# user stock controller
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:ticker])
    if stock.blank?
      stock = Stock.new_from_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:success] = "Stock #{@user_stock.stock.name}
                      was successfully added to portfolio"
    redirect_to my_portfolio_url
  end

  def destroy
    stock = current_user.user_stocks.find_by_stock_id(params[:id])
    stock.destroy
    flash[:notice] = "#{stock.stock.ticker} was successfully removed"
    redirect_to my_portfolio_url
  end
end


#<UserStock id: 43, user_id: 1, stock_id: 3, created_at: "2018-11-20 11:03:29", updated_at: "2018-11-20 11:03:29">, #<UserStock id: 39, user_id: 1, stock_id: 6, created_at: "2018-11-20 10:52:00", updated_at: "2018-11-20 10:52:00">, #<UserStock id: 40, user_id: 1, stock_id:16, created_at: "2018-11-20 10:55:48", updated_at: "2018-11-20 10:55:48">, #<UserStock id: 44, user_id: 1, stock_id: 19, created_at: "2018-11-20 11:05:08", updated_at: "2018-11-20 11:05:08">, #<UserStock id: 45, user_id: 1, stock_id: 20, created_at: "2018-11-20 11:09:02", updated_at: "2018-11-20 11:09:02">]>

app/controllers/users_controller.rb
# User
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @ustocks = current_user.stocks
  end

  def friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @ustocks = @user.stocks
  end

  def searchu
    if params[:user].blank?
      flash.now[:danger] = 'You entered empty search string'
    else
      @my_friends = current_user.friends.pluck(:id)
      @result = User.where(['email LIKE ? or last_name LIKE ? or first_name LIKE ?',
                          "%#{params[:user]}%", "%#{params[:user]}%",
                          "%#{params[:user]}%"]).where.not(id: current_user.id).uniq
      flash.now[:danger] = 'No match found' if @result.empty?
    end
  end
  respond_to do |format|
    format.js { render partial: 'user/user_results' }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">FinanceTracker</a>
    <% if current_user %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "My portflio", my_portfolio_url %></li>
        <li><%= link_to "Edit profile", edit_user_registration_url %></li>
        <li><%= link_to "My Friends", friends_url %></li>
      </ul>
      <ul class="nav navbar-right col-md-4">
        <li class="col-md-8 user-name text-right">
        <i class="fa fa-user"></i>
        <%= current_user.full_name%>
        </li>
        <li class="col-md-4 logout">
        <%= link_to("logout", destroy_user_session_path,
        class: "btn btn-xs btn-danger", method: :delete) %>
        </li>
      </ul>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer>
    <p>&copy; Company 2018</p>
  </footer>
</div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  <%= render 'layouts/nav' %>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="table-responsive"> 
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Symbol</th>
        <th>Current price</th>
        <% if current_user.id == @user.id %>
          <th>Action</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @ustocks.each do |a|%>
        <tr>
          <td><%= a.name%></td>
          <td><%= a.ticker%></td>
          <td><%= a.last_price%></td>
          <% if current_user.id == @user.id %>
          <td> <%= link_to 'Delete this stock', user_stock_url(a), method: :delete,
                  data: {confirm: 'Are you sure ?'}, class: "btn btn-danger btn-xs" %> 
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_friend_list.html.erb
<div class="table-responsive"> 
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |a|%>
        <tr>
          <td><%= a.full_name.capitalize %></td>
          <td><%= a.email %></td>
          <td><%= link_to "View Profile", user_url(a),
                  class: "btn btn-primary btn-xs" %>
              <%= link_to "Remove Friend", friendship_url(a), method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_friend_search.html.erb
<div id="user-lookup">
  <h3>Search for users</h3>
  <%= form_with url: search_users_url, method: :get, id: :user_lookup_form do |form| %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10" id='text-field'>
        <%= form.text_field :user, placeholder: "Search by name or email", autofocus: true,
                            class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= form.button type: :submit, class: "btn btn-lg btn-success" do %>
          <i class="fa fa-search"></i> Search user
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="user_search">
</div>

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>
<% if @stock.present? %>
 <div class="well results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_add_stock?(@stock.ticker) %>
      <%= link_to 'add to my stock',
                  user_stocks_path(ticker: @stock.ticker),
                  class: "btn btn-xs btn-success", method: :post, remote: true%>
    <% else %>
      <span class="label label-default">
        <% if !current_user.under_stock_limit? %>
          Tracking 10 stocks already
       <%elsif current_user.stock_already_added?(@stock.ticker) %>
         Already tracking this stock
       <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_user_results.html.erb
<% if params[:action] == 'searchu' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>

<% if @result.present? %>
<div class="well results-block">
  <table class="search-results-table col-md-12">
    <tbody>
      <% @result.each do |item| %>
          <tr>
            <td><strong>Name:</strong> <%= item.  full_name %></td>
            <td style="padding: 5px;"><strong>Email:</strong> <%= item.email %></td>
            <td><strong>Profile:</strong> <%= link_to "View Profile", user_url(item),
                                          class: "btn btn-xs btn-primary" ,style: "margin: 5px;"%>
              <% if @my_friends.include?(item.id)%>
                <span class="label label-default">
                    Already added
              <% else %>
                <%= link_to 'Add to friends',add_url(friend:item),
                    class: "btn btn-xs btn-success", method: :post%>
              <% end %>
                </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/friends.html.erb
<h1>Friends</h1>

<%= render 'friend_search' %>

<% if @friends.count > 0 %>
  <%= render 'friend_list' %>
<% else %>
  <p>Add some friends</p>
<% end %>

app/views/users/my_portfolio.html.erb
<h3>Search for Stocks</h3>
<div id="stock-lookup">
  <%= form_with url: search_stock_url, method: :get, id: :stock_lookup_form do |form| %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10" id='text-field'>
        <%= form.text_field :stock, placeholder: "Stock ticker symbol", autofocus: true,
                            class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= form.button type: :submit, class: "btn btn-lg btn-success" do %>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>

      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>
<div>
  <%= render 'stocks/list' %>
</div>

app/views/users/search.js.erb
$('#results').html("<%= j (render "users/result") %>") 

app/views/users/searchu.js.erb
$('#user_search').html("<%= j (render "users/user_results") %>") 

app/views/users/show.html.erb
<%= render 'stocks/list' %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>This is a stock trading app based on the NASDAQ index.
Refer <a href="https://www.cnbc.com/nasdaq-100/" target="_blank">Stock list</a> to add/ remove stock.</p>
<p>Add me up and check the stocks I'm tracking, Go to `My friends` -> Search -> ankit</p>